sudo: required
language: python
python: 3.6
services:
  - docker
cache: pip
install:
  - ./setup
  - pip install coveralls
script:
  - docker run --rm -i lukasmartinelli/hadolint < Dockerfile
  - coverage run rosie.py test
  - python rosie.py run federal_senate
after_success:
  - coveralls
