dist: trusty
language: python
sudo: required
python: 3.6
cache: pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagick
  - sudo apt-get install -y ghostscript
  - travis_retry composer self-update
install:
  - ./setup
  - pip install coveralls
script:
  - coverage run rosie.py test
  - python rosie.py run federal_senate
after_success:
  - coveralls
