dist: trusty
language: python
python: 3.6
cache: pip
directories:
  - tmp
install:
  - ./setup
  - pip install coveralls
script:
  - coverage run rosie.py test
  - python rosie.py run federal_senate
after_success:
  - coveralls
