dist: trusty
language: python
sudo: required
python: 3.6
cache: pip
install:
  - ./setup
  - pip install coveralls
script:
  - coverage run rosie.py test
  - python rosie.py run federal_senate
after_success:
  - coveralls
